// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cefhost.proto
// Protobuf C++ Version: 6.31.1

#include "cefhost.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cefhost {

inline constexpr Param::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Param::Param(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Param_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ParamDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParamDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParamDefaultTypeInternal() {}
  union {
    Param _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParamDefaultTypeInternal _Param_default_instance_;

inline constexpr ParamList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : items_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ParamList::ParamList(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ParamList_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ParamListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParamListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParamListDefaultTypeInternal() {}
  union {
    ParamList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParamListDefaultTypeInternal _ParamList_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR CefResponse_ParamMapEntry_DoNotUse::CefResponse_ParamMapEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : CefResponse_ParamMapEntry_DoNotUse::MapEntry(CefResponse_ParamMapEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : CefResponse_ParamMapEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CefResponse_ParamMapEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CefResponse_ParamMapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CefResponse_ParamMapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    CefResponse_ParamMapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CefResponse_ParamMapEntry_DoNotUseDefaultTypeInternal _CefResponse_ParamMapEntry_DoNotUse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR CefRequest_ParamMapEntry_DoNotUse::CefRequest_ParamMapEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : CefRequest_ParamMapEntry_DoNotUse::MapEntry(CefRequest_ParamMapEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : CefRequest_ParamMapEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CefRequest_ParamMapEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CefRequest_ParamMapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CefRequest_ParamMapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    CefRequest_ParamMapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CefRequest_ParamMapEntry_DoNotUseDefaultTypeInternal _CefRequest_ParamMapEntry_DoNotUse_default_instance_;

inline constexpr CefResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : paramlist_{},
        parammap_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CefResponse::CefResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CefResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CefResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CefResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CefResponseDefaultTypeInternal() {}
  union {
    CefResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CefResponseDefaultTypeInternal _CefResponse_default_instance_;

inline constexpr CefRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : paramlist_{},
        parammap_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CefRequest::CefRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CefRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CefRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CefRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CefRequestDefaultTypeInternal() {}
  union {
    CefRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CefRequestDefaultTypeInternal _CefRequest_default_instance_;
}  // namespace cefhost
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_cefhost_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_cefhost_2eproto = nullptr;
const ::uint32_t
    TableStruct_cefhost_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::cefhost::ParamList, _impl_.items_),
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::cefhost::Param, _impl_._oneof_case_[0]),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::cefhost::Param, _impl_.value_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cefhost::CefRequest_ParamMapEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cefhost::CefRequest_ParamMapEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::cefhost::CefRequest_ParamMapEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::cefhost::CefRequest, _impl_.paramlist_),
        PROTOBUF_FIELD_OFFSET(::cefhost::CefRequest, _impl_.parammap_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cefhost::CefResponse_ParamMapEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cefhost::CefResponse_ParamMapEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::cefhost::CefResponse_ParamMapEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::cefhost::CefResponse, _impl_.paramlist_),
        PROTOBUF_FIELD_OFFSET(::cefhost::CefResponse, _impl_.parammap_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::cefhost::ParamList)},
        {2, sizeof(::cefhost::Param)},
        {15, sizeof(::cefhost::CefRequest_ParamMapEntry_DoNotUse)},
        {22, sizeof(::cefhost::CefRequest)},
        {25, sizeof(::cefhost::CefResponse_ParamMapEntry_DoNotUse)},
        {32, sizeof(::cefhost::CefResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::cefhost::_ParamList_default_instance_._instance,
    &::cefhost::_Param_default_instance_._instance,
    &::cefhost::_CefRequest_ParamMapEntry_DoNotUse_default_instance_._instance,
    &::cefhost::_CefRequest_default_instance_._instance,
    &::cefhost::_CefResponse_ParamMapEntry_DoNotUse_default_instance_._instance,
    &::cefhost::_CefResponse_default_instance_._instance,
};
const char descriptor_table_protodef_cefhost_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rcefhost.proto\022\007cefhost\"*\n\tParamList\022\035\n"
    "\005items\030\001 \003(\0132\016.cefhost.Param\"\346\001\n\005Param\022\020"
    "\n\006intVal\030\001 \001(\005H\000\022\021\n\007uintVal\030\002 \001(\rH\000\022\022\n\010i"
    "nt64Val\030\003 \001(\003H\000\022\023\n\tuint64Val\030\004 \001(\004H\000\022\020\n\006"
    "strVal\030\005 \001(\tH\000\022\021\n\007boolVal\030\006 \001(\010H\000\022\023\n\tdou"
    "bleVal\030\007 \001(\001H\000\022\022\n\010floatVal\030\010 \001(\002H\000\022\020\n\006bi"
    "nVal\030\t \001(\014H\000\022&\n\010arrayVal\030\n \001(\0132\022.cefhost"
    ".ParamListH\000B\007\n\005value\"\245\001\n\nCefRequest\022!\n\t"
    "paramList\030\001 \003(\0132\016.cefhost.Param\0223\n\010param"
    "Map\030\002 \003(\0132!.cefhost.CefRequest.ParamMapE"
    "ntry\032\?\n\rParamMapEntry\022\013\n\003key\030\001 \001(\t\022\035\n\005va"
    "lue\030\002 \001(\0132\016.cefhost.Param:\0028\001\"\247\001\n\013CefRes"
    "ponse\022!\n\tparamList\030\001 \003(\0132\016.cefhost.Param"
    "\0224\n\010paramMap\030\002 \003(\0132\".cefhost.CefResponse"
    ".ParamMapEntry\032\?\n\rParamMapEntry\022\013\n\003key\030\001"
    " \001(\t\022\035\n\005value\030\002 \001(\0132\016.cefhost.Param:\0028\001b"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_cefhost_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cefhost_2eproto = {
    false,
    false,
    647,
    descriptor_table_protodef_cefhost_2eproto,
    "cefhost.proto",
    &descriptor_table_cefhost_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_cefhost_2eproto::offsets,
    file_level_enum_descriptors_cefhost_2eproto,
    file_level_service_descriptors_cefhost_2eproto,
};
namespace cefhost {
// ===================================================================

class ParamList::_Internal {
 public:
};

ParamList::ParamList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParamList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cefhost.ParamList)
}
PROTOBUF_NDEBUG_INLINE ParamList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cefhost::ParamList& from_msg)
      : items_{visibility, arena, from.items_},
        _cached_size_{0} {}

ParamList::ParamList(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ParamList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParamList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ParamList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cefhost.ParamList)
}
PROTOBUF_NDEBUG_INLINE ParamList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : items_{visibility, arena},
        _cached_size_{0} {}

inline void ParamList::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ParamList::~ParamList() {
  // @@protoc_insertion_point(destructor:cefhost.ParamList)
  SharedDtor(*this);
}
inline void ParamList::SharedDtor(MessageLite& self) {
  ParamList& this_ = static_cast<ParamList&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ParamList::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ParamList(arena);
}
constexpr auto ParamList::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ParamList, _impl_.items_) +
          decltype(ParamList::_impl_.items_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ParamList), alignof(ParamList), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ParamList::PlacementNew_,
                                 sizeof(ParamList),
                                 alignof(ParamList));
  }
}
constexpr auto ParamList::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ParamList_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ParamList::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ParamList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ParamList::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ParamList>(), &ParamList::ByteSizeLong,
              &ParamList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ParamList, _impl_._cached_size_),
          false,
      },
      &ParamList::kDescriptorMethods,
      &descriptor_table_cefhost_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ParamList_class_data_ =
        ParamList::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ParamList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ParamList_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ParamList_class_data_.tc_table);
  return ParamList_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
ParamList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ParamList_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cefhost::ParamList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .cefhost.Param items = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ParamList, _impl_.items_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .cefhost.Param items = 1;
    {PROTOBUF_FIELD_OFFSET(ParamList, _impl_.items_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cefhost::Param>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ParamList::Clear() {
// @@protoc_insertion_point(message_clear_start:cefhost.ParamList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ParamList::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ParamList& this_ = static_cast<const ParamList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ParamList::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ParamList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cefhost.ParamList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .cefhost.Param items = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_items_size());
       i < n; i++) {
    const auto& repfield = this_._internal_items().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cefhost.ParamList)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ParamList::ByteSizeLong(const MessageLite& base) {
  const ParamList& this_ = static_cast<const ParamList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ParamList::ByteSizeLong() const {
  const ParamList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cefhost.ParamList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .cefhost.Param items = 1;
    {
      total_size += 1UL * this_._internal_items_size();
      for (const auto& msg : this_._internal_items()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ParamList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ParamList*>(&to_msg);
  auto& from = static_cast<const ParamList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cefhost.ParamList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_items()->MergeFrom(
      from._internal_items());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ParamList::CopyFrom(const ParamList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cefhost.ParamList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ParamList::InternalSwap(ParamList* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
}

::google::protobuf::Metadata ParamList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Param::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::cefhost::Param, _impl_._oneof_case_);
};

void Param::set_allocated_arrayval(::cefhost::ParamList* PROTOBUF_NULLABLE arrayval) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (arrayval) {
    ::google::protobuf::Arena* submessage_arena = arrayval->GetArena();
    if (message_arena != submessage_arena) {
      arrayval = ::google::protobuf::internal::GetOwnedMessage(message_arena, arrayval, submessage_arena);
    }
    set_has_arrayval();
    _impl_.value_.arrayval_ = arrayval;
  }
  // @@protoc_insertion_point(field_set_allocated:cefhost.Param.arrayVal)
}
Param::Param(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Param_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cefhost.Param)
}
PROTOBUF_NDEBUG_INLINE Param::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cefhost::Param& from_msg)
      : value_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Param::Param(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Param& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Param_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Param* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (value_case()) {
    case VALUE_NOT_SET:
      break;
      case kIntVal:
        _impl_.value_.intval_ = from._impl_.value_.intval_;
        break;
      case kUintVal:
        _impl_.value_.uintval_ = from._impl_.value_.uintval_;
        break;
      case kInt64Val:
        _impl_.value_.int64val_ = from._impl_.value_.int64val_;
        break;
      case kUint64Val:
        _impl_.value_.uint64val_ = from._impl_.value_.uint64val_;
        break;
      case kStrVal:
        new (&_impl_.value_.strval_) decltype(_impl_.value_.strval_){arena, from._impl_.value_.strval_};
        break;
      case kBoolVal:
        _impl_.value_.boolval_ = from._impl_.value_.boolval_;
        break;
      case kDoubleVal:
        _impl_.value_.doubleval_ = from._impl_.value_.doubleval_;
        break;
      case kFloatVal:
        _impl_.value_.floatval_ = from._impl_.value_.floatval_;
        break;
      case kBinVal:
        new (&_impl_.value_.binval_) decltype(_impl_.value_.binval_){arena, from._impl_.value_.binval_};
        break;
      case kArrayVal:
        _impl_.value_.arrayval_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.value_.arrayval_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:cefhost.Param)
}
PROTOBUF_NDEBUG_INLINE Param::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Param::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Param::~Param() {
  // @@protoc_insertion_point(destructor:cefhost.Param)
  SharedDtor(*this);
}
inline void Param::SharedDtor(MessageLite& self) {
  Param& this_ = static_cast<Param&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_value()) {
    this_.clear_value();
  }
  this_._impl_.~Impl_();
}

void Param::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:cefhost.Param)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (value_case()) {
    case kIntVal: {
      // No need to clear
      break;
    }
    case kUintVal: {
      // No need to clear
      break;
    }
    case kInt64Val: {
      // No need to clear
      break;
    }
    case kUint64Val: {
      // No need to clear
      break;
    }
    case kStrVal: {
      _impl_.value_.strval_.Destroy();
      break;
    }
    case kBoolVal: {
      // No need to clear
      break;
    }
    case kDoubleVal: {
      // No need to clear
      break;
    }
    case kFloatVal: {
      // No need to clear
      break;
    }
    case kBinVal: {
      _impl_.value_.binval_.Destroy();
      break;
    }
    case kArrayVal: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.arrayval_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.arrayval_);
      }
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


inline void* PROTOBUF_NONNULL Param::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Param(arena);
}
constexpr auto Param::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Param),
                                            alignof(Param));
}
constexpr auto Param::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Param_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Param::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Param>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Param::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Param>(), &Param::ByteSizeLong,
              &Param::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Param, _impl_._cached_size_),
          false,
      },
      &Param::kDescriptorMethods,
      &descriptor_table_cefhost_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Param_class_data_ =
        Param::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Param::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Param_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Param_class_data_.tc_table);
  return Param_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 10, 1, 36, 2>
Param::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    10, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Param_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cefhost::Param>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 intVal = 1;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.intval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // uint32 uintVal = 2;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.uintval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUInt32)},
    // int64 int64Val = 3;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.int64val_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // uint64 uint64Val = 4;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.uint64val_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUInt64)},
    // string strVal = 5;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.strval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool boolVal = 6;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.boolval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBool)},
    // double doubleVal = 7;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.doubleval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // float floatVal = 8;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.floatval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kFloat)},
    // bytes binVal = 9;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.binval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBytes | ::_fl::kRepAString)},
    // .cefhost.ParamList arrayVal = 10;
    {PROTOBUF_FIELD_OFFSET(Param, _impl_.value_.arrayval_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cefhost::ParamList>()},
  }},
  {{
    "\15\0\0\0\0\6\0\0\0\0\0\0\0\0\0\0"
    "cefhost.Param"
    "strVal"
  }},
};
PROTOBUF_NOINLINE void Param::Clear() {
// @@protoc_insertion_point(message_clear_start:cefhost.Param)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_value();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Param::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Param& this_ = static_cast<const Param&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Param::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Param& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cefhost.Param)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.value_case()) {
    case kIntVal: {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_intval(), target);
      break;
    }
    case kUintVal: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_uintval(), target);
      break;
    }
    case kInt64Val: {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_int64val(), target);
      break;
    }
    case kUint64Val: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_uint64val(), target);
      break;
    }
    case kStrVal: {
      const ::std::string& _s = this_._internal_strval();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cefhost.Param.strVal");
      target = stream->WriteStringMaybeAliased(5, _s, target);
      break;
    }
    case kBoolVal: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          6, this_._internal_boolval(), target);
      break;
    }
    case kDoubleVal: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          7, this_._internal_doubleval(), target);
      break;
    }
    case kFloatVal: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          8, this_._internal_floatval(), target);
      break;
    }
    case kBinVal: {
      const ::std::string& _s = this_._internal_binval();
      target = stream->WriteBytesMaybeAliased(9, _s, target);
      break;
    }
    case kArrayVal: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          10, *this_._impl_.value_.arrayval_, this_._impl_.value_.arrayval_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cefhost.Param)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Param::ByteSizeLong(const MessageLite& base) {
  const Param& this_ = static_cast<const Param&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Param::ByteSizeLong() const {
  const Param& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cefhost.Param)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.value_case()) {
    // int32 intVal = 1;
    case kIntVal: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_intval());
      break;
    }
    // uint32 uintVal = 2;
    case kUintVal: {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_uintval());
      break;
    }
    // int64 int64Val = 3;
    case kInt64Val: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_int64val());
      break;
    }
    // uint64 uint64Val = 4;
    case kUint64Val: {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_uint64val());
      break;
    }
    // string strVal = 5;
    case kStrVal: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_strval());
      break;
    }
    // bool boolVal = 6;
    case kBoolVal: {
      total_size += 2;
      break;
    }
    // double doubleVal = 7;
    case kDoubleVal: {
      total_size += 9;
      break;
    }
    // float floatVal = 8;
    case kFloatVal: {
      total_size += 5;
      break;
    }
    // bytes binVal = 9;
    case kBinVal: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_binval());
      break;
    }
    // .cefhost.ParamList arrayVal = 10;
    case kArrayVal: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.value_.arrayval_);
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Param::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Param*>(&to_msg);
  auto& from = static_cast<const Param&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cefhost.Param)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_value();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kIntVal: {
        _this->_impl_.value_.intval_ = from._impl_.value_.intval_;
        break;
      }
      case kUintVal: {
        _this->_impl_.value_.uintval_ = from._impl_.value_.uintval_;
        break;
      }
      case kInt64Val: {
        _this->_impl_.value_.int64val_ = from._impl_.value_.int64val_;
        break;
      }
      case kUint64Val: {
        _this->_impl_.value_.uint64val_ = from._impl_.value_.uint64val_;
        break;
      }
      case kStrVal: {
        if (oneof_needs_init) {
          _this->_impl_.value_.strval_.InitDefault();
        }
        _this->_impl_.value_.strval_.Set(from._internal_strval(), arena);
        break;
      }
      case kBoolVal: {
        _this->_impl_.value_.boolval_ = from._impl_.value_.boolval_;
        break;
      }
      case kDoubleVal: {
        _this->_impl_.value_.doubleval_ = from._impl_.value_.doubleval_;
        break;
      }
      case kFloatVal: {
        _this->_impl_.value_.floatval_ = from._impl_.value_.floatval_;
        break;
      }
      case kBinVal: {
        if (oneof_needs_init) {
          _this->_impl_.value_.binval_.InitDefault();
        }
        _this->_impl_.value_.binval_.Set(from._internal_binval(), arena);
        break;
      }
      case kArrayVal: {
        if (oneof_needs_init) {
          _this->_impl_.value_.arrayval_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.value_.arrayval_);
        } else {
          _this->_impl_.value_.arrayval_->MergeFrom(*from._impl_.value_.arrayval_);
        }
        break;
      }
      case VALUE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Param::CopyFrom(const Param& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cefhost.Param)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Param::InternalSwap(Param* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Param::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
CefRequest_ParamMapEntry_DoNotUse::CefRequest_ParamMapEntry_DoNotUse()
    : SuperType(CefRequest_ParamMapEntry_DoNotUse_class_data_.base()) {}
CefRequest_ParamMapEntry_DoNotUse::CefRequest_ParamMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, CefRequest_ParamMapEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
CefRequest_ParamMapEntry_DoNotUse::CefRequest_ParamMapEntry_DoNotUse() : SuperType() {}
CefRequest_ParamMapEntry_DoNotUse::CefRequest_ParamMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL CefRequest_ParamMapEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CefRequest_ParamMapEntry_DoNotUse(arena);
}
constexpr auto CefRequest_ParamMapEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CefRequest_ParamMapEntry_DoNotUse),
                                            alignof(CefRequest_ParamMapEntry_DoNotUse));
}
constexpr auto CefRequest_ParamMapEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CefRequest_ParamMapEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CefRequest_ParamMapEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CefRequest_ParamMapEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CefRequest_ParamMapEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CefRequest_ParamMapEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CefRequest_ParamMapEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &CefRequest_ParamMapEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_cefhost_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CefRequest_ParamMapEntry_DoNotUse_class_data_ =
        CefRequest_ParamMapEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CefRequest_ParamMapEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CefRequest_ParamMapEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CefRequest_ParamMapEntry_DoNotUse_class_data_.tc_table);
  return CefRequest_ParamMapEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 44, 2>
CefRequest_ParamMapEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CefRequest_ParamMapEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CefRequest_ParamMapEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cefhost::CefRequest_ParamMapEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .cefhost.Param value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(CefRequest_ParamMapEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CefRequest_ParamMapEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(CefRequest_ParamMapEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .cefhost.Param value = 2;
    {PROTOBUF_FIELD_OFFSET(CefRequest_ParamMapEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cefhost::Param>()},
  }},
  {{
    "\40\3\0\0\0\0\0\0"
    "cefhost.CefRequest.ParamMapEntry"
    "key"
  }},
};
// ===================================================================

class CefRequest::_Internal {
 public:
};

CefRequest::CefRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CefRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cefhost.CefRequest)
}
PROTOBUF_NDEBUG_INLINE CefRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cefhost::CefRequest& from_msg)
      : paramlist_{visibility, arena, from.paramlist_},
        parammap_{visibility, arena, from.parammap_},
        _cached_size_{0} {}

CefRequest::CefRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CefRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CefRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CefRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cefhost.CefRequest)
}
PROTOBUF_NDEBUG_INLINE CefRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : paramlist_{visibility, arena},
        parammap_{visibility, arena},
        _cached_size_{0} {}

inline void CefRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CefRequest::~CefRequest() {
  // @@protoc_insertion_point(destructor:cefhost.CefRequest)
  SharedDtor(*this);
}
inline void CefRequest::SharedDtor(MessageLite& self) {
  CefRequest& this_ = static_cast<CefRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CefRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CefRequest(arena);
}
constexpr auto CefRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CefRequest, _impl_.paramlist_) +
          decltype(CefRequest::_impl_.paramlist_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CefRequest, _impl_.parammap_) +
          decltype(CefRequest::_impl_.parammap_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CefRequest, _impl_.parammap_) +
          decltype(CefRequest::_impl_.parammap_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(CefRequest), alignof(CefRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CefRequest::PlacementNew_,
                                 sizeof(CefRequest),
                                 alignof(CefRequest));
  }
}
constexpr auto CefRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CefRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CefRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CefRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CefRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CefRequest>(), &CefRequest::ByteSizeLong,
              &CefRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CefRequest, _impl_._cached_size_),
          false,
      },
      &CefRequest::kDescriptorMethods,
      &descriptor_table_cefhost_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CefRequest_class_data_ =
        CefRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CefRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CefRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CefRequest_class_data_.tc_table);
  return CefRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 3, 35, 2>
CefRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CefRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cefhost::CefRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .cefhost.Param paramList = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CefRequest, _impl_.paramlist_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .cefhost.Param paramList = 1;
    {PROTOBUF_FIELD_OFFSET(CefRequest, _impl_.paramlist_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // map<string, .cefhost.Param> paramMap = 2;
    {PROTOBUF_FIELD_OFFSET(CefRequest, _impl_.parammap_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cefhost::Param>()},
      {::_pbi::TcParser::GetMapAuxInfo(1, 0, 0,
                                       9, 11,
                                       0)},
      {::_pbi::TcParser::GetTable<::cefhost::Param>()},
  }},
  {{
    "\22\0\10\0\0\0\0\0"
    "cefhost.CefRequest"
    "paramMap"
  }},
};
PROTOBUF_NOINLINE void CefRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:cefhost.CefRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.paramlist_.Clear();
  _impl_.parammap_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CefRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CefRequest& this_ = static_cast<const CefRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CefRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CefRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cefhost.CefRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .cefhost.Param paramList = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_paramlist_size());
       i < n; i++) {
    const auto& repfield = this_._internal_paramlist().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // map<string, .cefhost.Param> paramMap = 2;
  if (!this_._internal_parammap().empty()) {
    using MapType = ::google::protobuf::Map<std::string, ::cefhost::Param>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, ::cefhost::Param,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = this_._internal_parammap();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            2, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cefhost.CefRequest.paramMap");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            2, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cefhost.CefRequest.paramMap");
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cefhost.CefRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CefRequest::ByteSizeLong(const MessageLite& base) {
  const CefRequest& this_ = static_cast<const CefRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CefRequest::ByteSizeLong() const {
  const CefRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cefhost.CefRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .cefhost.Param paramList = 1;
    {
      total_size += 1UL * this_._internal_paramlist_size();
      for (const auto& msg : this_._internal_paramlist()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // map<string, .cefhost.Param> paramMap = 2;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_parammap_size());
      for (const auto& entry : this_._internal_parammap()) {
        total_size += _pbi::MapEntryFuncs<std::string, ::cefhost::Param,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CefRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CefRequest*>(&to_msg);
  auto& from = static_cast<const CefRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cefhost.CefRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_paramlist()->MergeFrom(
      from._internal_paramlist());
  _this->_impl_.parammap_.MergeFrom(from._impl_.parammap_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CefRequest::CopyFrom(const CefRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cefhost.CefRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CefRequest::InternalSwap(CefRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.paramlist_.InternalSwap(&other->_impl_.paramlist_);
  _impl_.parammap_.InternalSwap(&other->_impl_.parammap_);
}

::google::protobuf::Metadata CefRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
CefResponse_ParamMapEntry_DoNotUse::CefResponse_ParamMapEntry_DoNotUse()
    : SuperType(CefResponse_ParamMapEntry_DoNotUse_class_data_.base()) {}
CefResponse_ParamMapEntry_DoNotUse::CefResponse_ParamMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, CefResponse_ParamMapEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
CefResponse_ParamMapEntry_DoNotUse::CefResponse_ParamMapEntry_DoNotUse() : SuperType() {}
CefResponse_ParamMapEntry_DoNotUse::CefResponse_ParamMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL CefResponse_ParamMapEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CefResponse_ParamMapEntry_DoNotUse(arena);
}
constexpr auto CefResponse_ParamMapEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CefResponse_ParamMapEntry_DoNotUse),
                                            alignof(CefResponse_ParamMapEntry_DoNotUse));
}
constexpr auto CefResponse_ParamMapEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CefResponse_ParamMapEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CefResponse_ParamMapEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CefResponse_ParamMapEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CefResponse_ParamMapEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CefResponse_ParamMapEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CefResponse_ParamMapEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &CefResponse_ParamMapEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_cefhost_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CefResponse_ParamMapEntry_DoNotUse_class_data_ =
        CefResponse_ParamMapEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CefResponse_ParamMapEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CefResponse_ParamMapEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CefResponse_ParamMapEntry_DoNotUse_class_data_.tc_table);
  return CefResponse_ParamMapEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 45, 2>
CefResponse_ParamMapEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CefResponse_ParamMapEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CefResponse_ParamMapEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cefhost::CefResponse_ParamMapEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .cefhost.Param value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(CefResponse_ParamMapEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CefResponse_ParamMapEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(CefResponse_ParamMapEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .cefhost.Param value = 2;
    {PROTOBUF_FIELD_OFFSET(CefResponse_ParamMapEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cefhost::Param>()},
  }},
  {{
    "\41\3\0\0\0\0\0\0"
    "cefhost.CefResponse.ParamMapEntry"
    "key"
  }},
};
// ===================================================================

class CefResponse::_Internal {
 public:
};

CefResponse::CefResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CefResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cefhost.CefResponse)
}
PROTOBUF_NDEBUG_INLINE CefResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cefhost::CefResponse& from_msg)
      : paramlist_{visibility, arena, from.paramlist_},
        parammap_{visibility, arena, from.parammap_},
        _cached_size_{0} {}

CefResponse::CefResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CefResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CefResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CefResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cefhost.CefResponse)
}
PROTOBUF_NDEBUG_INLINE CefResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : paramlist_{visibility, arena},
        parammap_{visibility, arena},
        _cached_size_{0} {}

inline void CefResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CefResponse::~CefResponse() {
  // @@protoc_insertion_point(destructor:cefhost.CefResponse)
  SharedDtor(*this);
}
inline void CefResponse::SharedDtor(MessageLite& self) {
  CefResponse& this_ = static_cast<CefResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CefResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CefResponse(arena);
}
constexpr auto CefResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CefResponse, _impl_.paramlist_) +
          decltype(CefResponse::_impl_.paramlist_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CefResponse, _impl_.parammap_) +
          decltype(CefResponse::_impl_.parammap_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CefResponse, _impl_.parammap_) +
          decltype(CefResponse::_impl_.parammap_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(CefResponse), alignof(CefResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CefResponse::PlacementNew_,
                                 sizeof(CefResponse),
                                 alignof(CefResponse));
  }
}
constexpr auto CefResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CefResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CefResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CefResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CefResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CefResponse>(), &CefResponse::ByteSizeLong,
              &CefResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CefResponse, _impl_._cached_size_),
          false,
      },
      &CefResponse::kDescriptorMethods,
      &descriptor_table_cefhost_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CefResponse_class_data_ =
        CefResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CefResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CefResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CefResponse_class_data_.tc_table);
  return CefResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 3, 36, 2>
CefResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CefResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cefhost::CefResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .cefhost.Param paramList = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CefResponse, _impl_.paramlist_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .cefhost.Param paramList = 1;
    {PROTOBUF_FIELD_OFFSET(CefResponse, _impl_.paramlist_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // map<string, .cefhost.Param> paramMap = 2;
    {PROTOBUF_FIELD_OFFSET(CefResponse, _impl_.parammap_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cefhost::Param>()},
      {::_pbi::TcParser::GetMapAuxInfo(1, 0, 0,
                                       9, 11,
                                       0)},
      {::_pbi::TcParser::GetTable<::cefhost::Param>()},
  }},
  {{
    "\23\0\10\0\0\0\0\0"
    "cefhost.CefResponse"
    "paramMap"
  }},
};
PROTOBUF_NOINLINE void CefResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:cefhost.CefResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.paramlist_.Clear();
  _impl_.parammap_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CefResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CefResponse& this_ = static_cast<const CefResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CefResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CefResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cefhost.CefResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .cefhost.Param paramList = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_paramlist_size());
       i < n; i++) {
    const auto& repfield = this_._internal_paramlist().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // map<string, .cefhost.Param> paramMap = 2;
  if (!this_._internal_parammap().empty()) {
    using MapType = ::google::protobuf::Map<std::string, ::cefhost::Param>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, ::cefhost::Param,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = this_._internal_parammap();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            2, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cefhost.CefResponse.paramMap");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            2, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cefhost.CefResponse.paramMap");
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cefhost.CefResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CefResponse::ByteSizeLong(const MessageLite& base) {
  const CefResponse& this_ = static_cast<const CefResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CefResponse::ByteSizeLong() const {
  const CefResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cefhost.CefResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .cefhost.Param paramList = 1;
    {
      total_size += 1UL * this_._internal_paramlist_size();
      for (const auto& msg : this_._internal_paramlist()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // map<string, .cefhost.Param> paramMap = 2;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_parammap_size());
      for (const auto& entry : this_._internal_parammap()) {
        total_size += _pbi::MapEntryFuncs<std::string, ::cefhost::Param,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CefResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CefResponse*>(&to_msg);
  auto& from = static_cast<const CefResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cefhost.CefResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_paramlist()->MergeFrom(
      from._internal_paramlist());
  _this->_impl_.parammap_.MergeFrom(from._impl_.parammap_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CefResponse::CopyFrom(const CefResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cefhost.CefResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CefResponse::InternalSwap(CefResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.paramlist_.InternalSwap(&other->_impl_.paramlist_);
  _impl_.parammap_.InternalSwap(&other->_impl_.parammap_);
}

::google::protobuf::Metadata CefResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cefhost
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cefhost_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
